FROM python:3.12-slim

WORKDIR /app

COPY . .

RUN pip install -r requirements.txt --default-timeout=30000
COPY requirements.txt .

EXPOSE 7537

# Run the Python application
CMD ["python3", "app.py"]
