FROM nvidia/cuda:12.2.2-devel-ubuntu22.04 AS app

ENV DEBIAN_FRONTEND=noninteractive \
    PIP_PREFER_BINARY=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_NO_CACHE_DIR=1 \
    PNPM_HOME=/usr/local/bin

# Install necessary dependencies, including OpenGL libraries
RUN apt-get update && apt-get install -y \
    software-properties-common \
    build-essential \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    wget \
    curl \
    git \
    libgl1-mesa-glx \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt-get update && apt-get install -y \
    python3.12 \
    python3.12-dev \
    python3.12-venv \
    && apt-get clean

# Install pip for Python 3.12
RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3.12

ENV PORT=7537
WORKDIR /apps
COPY . .

# Install Python dependencies
RUN pip install -r requirements.txt --default-timeout=30000

EXPOSE 7537

# Run the app with Gradio, running on host 0.0.0.0 to make it accessible
CMD ["python3.12", "app.py"]
